# Generated by Django 6.0.5 on 2026-05-11 12:20

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='อีเมล')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='โทรศัพท์')),
                ('is_staff', models.BooleanField(default=False, verbose_name='เข้า Django admin ได้')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สมัคร')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'เจ้าของ / แอดมิน'), ('manager', 'ผู้จัดการ / ผู้อนุมัติ'), ('sales', 'พนักงานขาย'), ('accounting', 'บัญชี / การเงิน'), ('installer', 'ช่าง / ทีมติดตั้ง'), ('viewer', 'ผู้ดูอย่างเดียว')], default='sales', max_length=20, verbose_name='บทบาท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('max_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ส่วนลดสูงสุดที่อนุมัติได้ (%)')),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='วงเงินที่อนุมัติได้ (บาท)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สมาชิก Workspace',
                'verbose_name_plural': 'สมาชิก Workspace',
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='uniq_membership_user_tenant')],
            },
        ),
    ]
