# Generated by Django 6.0.5 on 2026-05-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_see_all_records',
            field=models.BooleanField(default=True, help_text='ปิด = เห็นเฉพาะ lead / ดีล / ใบเสนอราคา ที่ตนรับผิดชอบ', verbose_name='เห็นข้อมูลของทุกคน'),
        ),
    ]
