# Generated by Django 6.0.5 on 2026-05-13 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_can_see_all_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(max_length=64, verbose_name='Secret (base32)')),
                ('confirmed', models.BooleanField(default=False, verbose_name='ยืนยันแล้ว')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='ยืนยันเมื่อ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ 2FA (TOTP)',
                'verbose_name_plural': 'อุปกรณ์ 2FA (TOTP)',
            },
        ),
    ]
