# Generated by Django 6.0.5 on 2026-05-13 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_salestarget_rls'),
        ('quotes', '0008_salesdocument_cancelled_reason_and_more'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='วันที่รับชำระ')),
                ('method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอนเงิน'), ('cheque', 'เช็ค'), ('card', 'บัตรเครดิต/เดบิต'), ('other', 'อื่นๆ')], default='transfer', max_length=20, verbose_name='วิธีชำระ')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='จำนวนเงินที่รับ')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ค่าธรรมเนียม')),
                ('withholding_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ภาษีหัก ณ ที่จ่ายที่ลูกค้าหักไว้')),
                ('withholding_cert_ref', models.CharField(blank=True, max_length=120, verbose_name='เลขที่หนังสือรับรองการหักภาษี')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='อ้างอิง (เลขที่เช็ค/สลิป)')),
                ('status', models.CharField(choices=[('recorded', 'บันทึกแล้ว'), ('cleared', 'เคลียร์แล้ว'), ('bounced', 'เช็คคืน')], default='recorded', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.customer')),
                ('receipt_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.salesdocument')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'การรับชำระเงิน',
                'verbose_name_plural': 'การรับชำระเงิน',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='จำนวนที่ตัดชำระ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='quotes.salesdocument')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'การตัดชำระ',
                'verbose_name_plural': 'การตัดชำระ',
            },
        ),
    ]
