# Generated by Django 6.0.5 on 2026-05-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(blank=True, max_length=50, verbose_name='Channel ID')),
                ('channel_secret', models.CharField(blank=True, max_length=100, verbose_name='Channel secret')),
                ('channel_access_token', models.TextField(blank=True, verbose_name='Channel access token')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'การเชื่อม LINE OA',
                'verbose_name_plural': 'การเชื่อม LINE OA',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_line_integration_per_tenant')],
            },
        ),
    ]
