# Generated by Django 6.0.5 on 2026-05-12 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_salestarget_rls'),
        ('integrations', '0002_rls'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('line', 'LINE')], default='line', max_length=20, verbose_name='ช่องทาง')),
                ('external_id', models.CharField(help_text='เช่น LINE user id', max_length=100, verbose_name='รหัสผู้ใช้ภายนอก')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อที่แสดง')),
                ('status', models.CharField(choices=[('open', 'เปิด'), ('snoozed', 'พักไว้'), ('closed', 'ปิด')], default='open', max_length=20, verbose_name='สถานะ')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='ข้อความล่าสุด')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='ตัวอย่างข้อความล่าสุด')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='ยังไม่อ่าน')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.lead')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'บทสนทนา',
                'verbose_name_plural': 'บทสนทนา',
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'ขาเข้า'), ('out', 'ขาออก')], max_length=4, verbose_name='ทิศทาง')),
                ('kind', models.CharField(choices=[('text', 'ข้อความ'), ('image', 'รูปภาพ'), ('sticker', 'สติกเกอร์'), ('file', 'ไฟล์'), ('video', 'วิดีโอ'), ('audio', 'เสียง'), ('location', 'ตำแหน่ง'), ('other', 'อื่น ๆ')], default='text', max_length=20, verbose_name='ชนิด')),
                ('text', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('media_url', models.URLField(blank=True, verbose_name='สื่อ')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='รหัสข้อความภายนอก')),
                ('ai_parsed', models.JSONField(blank=True, default=dict, verbose_name='ผลวิเคราะห์ AI')),
                ('sent_at', models.DateTimeField(verbose_name='เวลาส่ง')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.conversation')),
                ('sender_user', models.ForeignKey(blank=True, help_text='ผู้ส่ง (เฉพาะข้อความขาออกที่ส่งโดยพนักงาน)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ข้อความ',
                'verbose_name_plural': 'ข้อความ',
                'ordering': ('sent_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'status', '-last_message_at'], name='integration_tenant__b5a327_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'assigned_to'], name='integration_tenant__f503f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'external_id'), name='uniq_conversation_per_external_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='integration_convers_7d457b_idx'),
        ),
    ]
