# Generated by Django 6.0.5 on 2026-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อธุรกิจ')),
                ('slug', models.SlugField(help_text='ตัวระบุ workspace (ใช้เป็น subdomain ในอนาคต)', max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('plan', models.CharField(choices=[('trial', 'ทดลองใช้'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='แพ็กเกจ')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='วันสิ้นสุดทดลองใช้')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
    ]
