# Generated by Django 6.0.5 on 2026-05-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100, verbose_name='ธนาคาร')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='สาขา')),
                ('account_name', models.CharField(max_length=200, verbose_name='ชื่อบัญชี')),
                ('account_number', models.CharField(max_length=30, verbose_name='เลขที่บัญชี')),
                ('account_type', models.CharField(blank=True, help_text='เช่น ออมทรัพย์ / กระแสรายวัน', max_length=50, verbose_name='ประเภทบัญชี')),
                ('is_default', models.BooleanField(default=False, verbose_name='บัญชีหลัก')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'บัญชีธนาคาร',
                'verbose_name_plural': 'บัญชีธนาคาร',
                'ordering': ('-is_default', 'bank_name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_th', models.CharField(max_length=255, verbose_name='ชื่อบริษัท (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='ชื่อบริษัท (อังกฤษ)')),
                ('tax_id', models.CharField(blank=True, max_length=13, verbose_name='เลขประจำตัวผู้เสียภาษี (13 หลัก)')),
                ('branch_kind', models.CharField(choices=[('head', 'สำนักงานใหญ่'), ('branch', 'สาขา')], default='head', max_length=10, verbose_name='ประเภทสำนักงาน')),
                ('branch_code', models.CharField(blank=True, help_text='เช่น 00001', max_length=10, verbose_name='รหัสสาขา (ถ้ามี)')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('website', models.URLField(blank=True, verbose_name='เว็บไซต์')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='LINE')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='โลโก้')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ข้อมูลบริษัท',
                'verbose_name_plural': 'ข้อมูลบริษัท',
            },
        ),
    ]
