# Generated by Django 6.0.5 on 2026-05-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='ใช้เป็น subdomain: <slug>.<APP_DOMAIN>', max_length=63, unique=True),
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text='เช่น crm.example.com (ไม่ใส่ http://)', max_length=253, unique=True, verbose_name='โดเมน')),
                ('is_primary', models.BooleanField(default=False, verbose_name='โดเมนหลัก')),
                ('verified', models.BooleanField(default=False, verbose_name='ยืนยันความเป็นเจ้าของแล้ว')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Custom domain',
                'verbose_name_plural': 'Custom domains',
                'ordering': ('-is_primary', 'domain'),
            },
        ),
    ]
