# Generated by Django 6.0.5 on 2026-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'รายเดือน'), ('annual', 'รายปี')], default='monthly', max_length=20, verbose_name='รอบบิล'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_period_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='รอบปัจจุบันสิ้นสุด'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='วันเริ่มแพ็กเกจ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'ทดลองใช้'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('business', 'Business')], default='trial', max_length=20, verbose_name='แพ็กเกจ'),
        ),
    ]
