# Generated by Django 6.0.5 on 2026-05-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_billing_cycle_tenant_current_period_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.PositiveIntegerField(verbose_name='รอบเดือน (YYYYMM)')),
                ('kind', models.CharField(max_length=32, verbose_name='ประเภท')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='จำนวน')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'การใช้งาน',
                'verbose_name_plural': 'การใช้งาน',
                'indexes': [models.Index(fields=['tenant', 'period'], name='tenants_usa_tenant__c613fc_idx')],
                'unique_together': {('tenant', 'period', 'kind')},
            },
        ),
    ]
