# Generated by Django 6.0.5 on 2026-05-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_usage_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(help_text='เช่น billing, e_tax, white_label, custom_domain, api, priority_support, sla', max_length=64, verbose_name='รหัสโมดูล')),
                ('mode', models.CharField(choices=[('on', 'บังคับเปิด'), ('off', 'บังคับปิด')], default='on', max_length=10, verbose_name='โหมด')),
                ('reason', models.TextField(help_text='ลูกค้า anchor, รางวัล, รอ release ฯลฯ', verbose_name='เหตุผล')),
                ('expires_at', models.DateField(blank=True, help_text='เว้นว่าง = ถาวร', null=True, verbose_name='หมดอายุ')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'การ override โมดูล',
                'verbose_name_plural': 'การ override โมดูล',
                'ordering': ('tenant', 'module_code'),
                'unique_together': {('tenant', 'module_code')},
            },
        ),
    ]
