# Generated by Django 6.0.5 on 2026-05-14 07:29
# + data migration: rename plan=trial → plan=free (Trial tier dropped in PRD v2.2)

from django.db import migrations, models


def trial_to_free(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(plan="trial").update(plan="free")


def free_to_trial(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(plan="free").update(plan="trial")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenantfeatureoverride'),
    ]

    operations = [
        migrations.RunPython(trial_to_free, reverse_code=free_to_trial),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20, verbose_name='แพ็กเกจ'),
        ),
    ]
