# Generated by Django 6.0.5 on 2026-05-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='หัวข้อ')),
                ('subline', models.CharField(blank=True, max_length=300, verbose_name='รายละเอียด')),
                ('image', models.ImageField(upload_to='hero_banners/', verbose_name='ภาพ')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='ข้อความปุ่ม')),
                ('cta_url', models.URLField(blank=True, verbose_name='ปุ่มลิงก์ไปที่')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Hero banner',
                'verbose_name_plural': 'Hero banners',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_text', models.CharField(default='ใบเสนอราคา / QUOTATION', max_length=200, verbose_name='ข้อความหัวเอกสาร')),
                ('delivery_days', models.PositiveIntegerField(default=45, verbose_name='กำหนดส่งของ (วัน)')),
                ('validity_days', models.PositiveIntegerField(default=90, verbose_name='ยืนราคา (วัน)')),
                ('payment_terms', models.TextField(blank=True, default='โอนเข้าบัญชีธนาคารหลัก · ส่งสลิปยืนยันการโอน', verbose_name='เงื่อนไขการชำระเงิน')),
                ('deposit_text', models.CharField(blank=True, default='30% ก่อนเริ่มงาน', max_length=200, verbose_name='ชำระล่วงหน้า (deposit)')),
                ('after_delivery_text', models.CharField(blank=True, default='70% เมื่อรับมอบงาน', max_length=200, verbose_name='ชำระหลังส่งมอบ')),
                ('warranty_text', models.CharField(blank=True, default='1 ปี จากการใช้งานปกติ', max_length=200, verbose_name='การรับประกัน')),
                ('signer_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อผู้ลงนาม')),
                ('signer_phone', models.CharField(blank=True, max_length=40, verbose_name='เบอร์ผู้ลงนาม')),
                ('vat_enabled', models.BooleanField(default=True, verbose_name='เปิด VAT 7%')),
                ('wht_enabled', models.BooleanField(default=False, verbose_name='เปิด WHT 3% (หัก ณ ที่จ่าย)')),
                ('page2_layout', models.CharField(choices=[('none', 'ไม่มีหน้ารูป'), ('one', '1 รายการ/หน้า · รูปใหญ่'), ('two', '2 รายการ/หน้า'), ('grid4', 'Grid 4 รายการ/หน้า')], default='one', max_length=10, verbose_name='หน้ารูปสินค้า · เลย์เอาต์')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_template', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'เทมเพลตใบเสนอราคา',
                'verbose_name_plural': 'เทมเพลตใบเสนอราคา',
            },
        ),
    ]
