# Generated by Django 6.0.5 on 2026-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_herobanner_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('craft', 'Craft · warm classic'), ('atelier', 'Atelier · refined'), ('bauhaus', 'Bauhaus · bold modern'), ('velvet', 'Velvet · luxe dark')], db_index=True, default='craft', max_length=20, verbose_name='ธีมเว็บ tenant'),
        ),
    ]
