# Generated by Django 6.0.5 on 2026-05-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bulk_proposal_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=48, null=True, verbose_name='SLA bulk proposal (ชม.)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_certifications',
            field=models.CharField(blank=True, max_length=255, verbose_name='มาตรฐาน/ใบรับรอง (แสดง)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_free_install_min_thb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ติดตั้งฟรีขั้นต่ำ (บาท)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_response_sla_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=24, null=True, verbose_name='SLA ตอบกลับ (ชม.)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_sku_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวน SKU (เว็บ)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='showroom_address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่ showroom'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='showroom_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='เวลาเปิด showroom'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='showroom_maps_url',
            field=models.URLField(blank=True, verbose_name='Google Maps'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='showroom_parking',
            field=models.CharField(blank=True, max_length=120, verbose_name='ที่จอดรถ showroom'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='showroom_sqm',
            field=models.CharField(blank=True, max_length=120, verbose_name='พื้นที่ showroom'),
        ),
    ]
