# Generated by Django 6.0.5 on 2026-05-11 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_bankaccount_companyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='ชื่อ (อังกฤษ)')),
                ('kind', models.CharField(choices=[('company', 'นิติบุคคล'), ('individual', 'บุคคลธรรมดา')], default='company', max_length=20, verbose_name='ประเภท')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('branch_label', models.CharField(blank=True, help_text='เช่น "สำนักงานใหญ่" หรือ "สาขาที่ 00001"', max_length=50, verbose_name='สำนักงาน/สาขา')),
                ('billing_address', models.TextField(blank=True, verbose_name='ที่อยู่ออกใบกำกับภาษี')),
                ('shipping_address', models.TextField(blank=True, verbose_name='ที่อยู่จัดส่ง/หน้างาน')),
                ('default_credit_days', models.PositiveIntegerField(default=0, verbose_name='เครดิตเริ่มต้น (วัน)')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_archived', models.BooleanField(default=False, verbose_name='เก็บเข้าคลัง')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='ตำแหน่ง')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='แผนก')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='LINE')),
                ('is_primary', models.BooleanField(default=False, verbose_name='ผู้ติดต่อหลัก')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer')),
            ],
            options={
                'verbose_name': 'ผู้ติดต่อ',
                'verbose_name_plural': 'ผู้ติดต่อ',
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อดีล/โครงการ')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='มูลค่าโดยประมาณ')),
                ('probability', models.PositiveSmallIntegerField(default=0, verbose_name='โอกาสปิด (%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='คาดปิดวันที่')),
                ('channel', models.CharField(blank=True, choices=[('line', 'LINE'), ('facebook', 'Facebook/Messenger'), ('phone', 'โทรศัพท์'), ('web_form', 'ฟอร์มเว็บไซต์'), ('email', 'อีเมล'), ('walk_in', 'Walk-in / โชว์รูม'), ('exhibition', 'ออกบูธ/งานแฟร์'), ('ebidding', 'e-Bidding ภาครัฐ'), ('referral', 'แนะนำต่อ'), ('other', 'อื่น ๆ')], max_length=20, verbose_name='ช่องทาง')),
                ('source', models.CharField(blank=True, help_text='เช่น ชื่อแคมเปญ / ผู้แนะนำ', max_length=255, verbose_name='แหล่งที่มา')),
                ('status', models.CharField(choices=[('open', 'เปิดอยู่'), ('won', 'ปิดได้'), ('lost', 'ปิดไม่ได้')], default='open', max_length=10, verbose_name='สถานะ')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name='เหตุผลที่แพ้')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='ปิดเมื่อ')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ดีล',
                'verbose_name_plural': 'ดีล',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call', 'โทรศัพท์'), ('line', 'LINE'), ('email', 'อีเมล'), ('meeting', 'ประชุม/นัดพบ'), ('site_visit', 'สำรวจหน้างาน'), ('note', 'บันทึก')], default='note', max_length=20, verbose_name='ประเภท')),
                ('body', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เกิดขึ้นเมื่อ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
            ],
            options={
                'verbose_name': 'กิจกรรม',
                'verbose_name_plural': 'กิจกรรม',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อขั้น')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('kind', models.CharField(choices=[('open', 'กำลังดำเนินการ'), ('won', 'ปิดได้'), ('lost', 'ปิดไม่ได้')], default='open', max_length=10, verbose_name='ประเภท')),
                ('default_probability', models.PositiveSmallIntegerField(default=0, help_text='0–100', verbose_name='โอกาสปิด (%)')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ขั้นใน Pipeline',
                'verbose_name_plural': 'ขั้นใน Pipeline',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipelinestage'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('callback', 'โทรกลับ'), ('send_sample', 'ส่งตัวอย่าง/สี'), ('site_survey', 'นัดสำรวจหน้างาน'), ('send_quote', 'ส่งใบเสนอราคา'), ('follow_up', 'ติดตาม'), ('other', 'อื่น ๆ')], default='follow_up', max_length=20, verbose_name='ประเภท')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='รายละเอียด')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='กำหนดเสร็จ')),
                ('status', models.CharField(choices=[('open', 'ค้างอยู่'), ('done', 'เสร็จแล้ว'), ('cancelled', 'ยกเลิก')], default='open', max_length=10, verbose_name='สถานะ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='เสร็จเมื่อ')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'งาน',
                'verbose_name_plural': 'งาน',
                'ordering': ('due_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'name'], name='crm_custome_tenant__98841d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['tenant', 'status', 'stage'], name='crm_deal_tenant__46efc9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'assignee', 'status'], name='crm_task_tenant__d8b837_idx'),
        ),
    ]
