# Generated by Django 6.0.5 on 2026-05-11 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rls'),
        ('tenants', '0003_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ติดต่อ')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='บริษัท/หน่วยงาน')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='LINE')),
                ('channel', models.CharField(choices=[('line', 'LINE'), ('facebook', 'Facebook/Messenger'), ('phone', 'โทรศัพท์'), ('web_form', 'ฟอร์มเว็บไซต์'), ('email', 'อีเมล'), ('walk_in', 'Walk-in / โชว์รูม'), ('exhibition', 'ออกบูธ/งานแฟร์'), ('ebidding', 'e-Bidding ภาครัฐ'), ('referral', 'แนะนำต่อ'), ('other', 'อื่น ๆ')], default='web_form', max_length=20, verbose_name='ช่องทาง')),
                ('source', models.CharField(blank=True, help_text='เช่น ชื่อแคมเปญ / ผู้แนะนำ', max_length=255, verbose_name='แหล่งที่มา')),
                ('product_interest', models.CharField(blank=True, max_length=255, verbose_name='สินค้าที่สนใจ')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='งบประมาณโดยประมาณ')),
                ('message', models.TextField(blank=True, verbose_name='ข้อความ')),
                ('status', models.CharField(choices=[('new', 'ใหม่'), ('qualified', 'คัดกรองแล้ว'), ('converted', 'แปลงเป็นดีลแล้ว'), ('disqualified', 'ไม่ผ่านคัดกรอง')], default='new', max_length=20, verbose_name='สถานะ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.deal')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'status'], name='crm_lead_tenant__3e1c47_idx')],
            },
        ),
    ]
