# Generated by Django 6.0.5 on 2026-05-12 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activity_lead'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='ปี (ค.ศ.)')),
                ('month', models.PositiveSmallIntegerField(verbose_name='เดือน (1–12)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='เป้ายอดขาย (บาท)')),
                ('salesperson', models.ForeignKey(blank=True, help_text='เว้นว่าง = เป้าของทั้งทีม', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'เป้ายอดขาย',
                'verbose_name_plural': 'เป้ายอดขาย',
                'ordering': ('-year', '-month'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'salesperson', 'year', 'month'), name='uniq_sales_target')],
            },
        ),
    ]
