# Generated by Django 6.0.5 on 2026-05-11 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_rls'),
        ('crm', '0004_lead_rls'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('quotation', 'ใบเสนอราคา')], default='quotation', max_length=20, verbose_name='ชนิดเอกสาร')),
                ('doc_number', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='เลขที่เอกสาร')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='เลขที่แก้ไข (Rev.)')),
                ('issue_date', models.DateField(verbose_name='วันที่ออก')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ยืนราคาถึง')),
                ('reference', models.CharField(blank=True, help_text='เช่น ชื่อโครงการ / RFQ ของลูกค้า', max_length=255, verbose_name='อ้างอิง')),
                ('currency', models.CharField(default='THB', max_length=3, verbose_name='สกุลเงิน')),
                ('price_mode', models.CharField(choices=[('excl', 'ราคาไม่รวม VAT'), ('incl', 'ราคารวม VAT แล้ว')], default='excl', max_length=4, verbose_name='รูปแบบราคา')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('pending', 'รออนุมัติ'), ('ready', 'พร้อมส่ง'), ('sent', 'ส่งให้ลูกค้าแล้ว'), ('accepted', 'ลูกค้าตอบรับ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('expired', 'หมดอายุ'), ('cancelled', 'ยกเลิก')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('end_discount_kind', models.CharField(choices=[('amount', 'บาท'), ('percent', '%')], default='amount', max_length=10, verbose_name='ชนิดส่วนลดท้ายบิล')),
                ('end_discount_value', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='ส่วนลดท้ายบิล')),
                ('payment_terms', models.TextField(blank=True, verbose_name='เงื่อนไขการชำระเงิน')),
                ('lead_time', models.CharField(blank=True, max_length=255, verbose_name='กำหนดส่งมอบ/ติดตั้ง')),
                ('warranty', models.CharField(blank=True, max_length=255, verbose_name='การรับประกัน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ/เงื่อนไขอื่น')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.bankaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='crm.customer')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.deal')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_documents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'เอกสารขาย',
                'verbose_name_plural': 'เอกสารขาย',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalesDocLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_label', models.CharField(blank=True, max_length=120, verbose_name='ห้อง/โซน')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('line_type', models.CharField(choices=[('item', 'รายการ'), ('heading', 'หัวข้อ/กลุ่ม'), ('note', 'ข้อความ')], default='item', max_length=10, verbose_name='ชนิดบรรทัด')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('dimensions', models.CharField(blank=True, max_length=120, verbose_name='ขนาด W×D×H')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='วัสดุ/สี')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quote_lines/', verbose_name='รูปประกอบ')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='จำนวน')),
                ('unit', models.CharField(default='ชิ้น', max_length=30, verbose_name='หน่วย')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ราคา/หน่วย')),
                ('discount_kind', models.CharField(choices=[('amount', 'บาท'), ('percent', '%')], default='amount', max_length=10, verbose_name='ชนิดส่วนลด')),
                ('discount_value', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='ส่วนลด')),
                ('tax_type', models.CharField(choices=[('vat7', 'VAT 7%'), ('vat0', 'VAT 0% (เช่น ส่งออก)'), ('exempt', 'ยกเว้น VAT'), ('none', 'ไม่คิด VAT')], default='vat7', max_length=10, verbose_name='ภาษี')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='หัก ณ ที่จ่าย (%)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.salesdocument')),
            ],
            options={
                'verbose_name': 'บรรทัดในเอกสาร',
                'verbose_name_plural': 'บรรทัดในเอกสาร',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('quotation', 'ใบเสนอราคา')], max_length=20)),
                ('year', models.PositiveIntegerField(help_text='ปีของเลขที่เอกสาร (พ.ศ.)')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ลำดับเลขที่เอกสาร',
                'verbose_name_plural': 'ลำดับเลขที่เอกสาร',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'doc_type', 'year'), name='uniq_docseq_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['tenant', 'doc_type', 'status'], name='quotes_sale_tenant__c6777e_idx'),
        ),
    ]
