# Generated by Django 6.0.5 on 2026-05-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rls'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='customer_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ตอบกลับเมื่อ'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='customer_response',
            field=models.CharField(blank=True, choices=[('accepted', 'ยอมรับ'), ('changes', 'ขอแก้ไข'), ('rejected', 'ปฏิเสธ')], max_length=10, verbose_name='การตอบกลับของลูกค้า'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='customer_response_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ที่ตอบกลับ'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='customer_response_note',
            field=models.TextField(blank=True, verbose_name='ข้อความจากลูกค้า'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='customer_signed_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ลงชื่อโดย'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ส่งให้ลูกค้าเมื่อ'),
        ),
        migrations.CreateModel(
            name='QuotationShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='quotes.salesdocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_share_links', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ลิงก์แชร์ใบเสนอราคา',
                'verbose_name_plural': 'ลิงก์แชร์ใบเสนอราคา',
            },
        ),
    ]
