# Generated by Django 6.0.5 on 2026-05-11 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_salesdocument_customer_responded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='อนุมัติเมื่อ'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
