# Generated by Django 6.0.5 on 2026-05-11 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_salesdocument_approved_at_salesdocument_approved_by'),
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='revision_note',
            field=models.CharField(blank=True, help_text='ใส่ตอนกด “เปิดแก้ไขใหม่”; จะถูกบันทึกลงในเวอร์ชันถัดไปที่ส่ง', max_length=255, verbose_name='เหตุผลของการแก้ไขล่าสุด'),
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(verbose_name='เลขที่แก้ไข (Rev.)')),
                ('snapshot', models.JSONField(verbose_name='ข้อมูล ณ ตอนส่ง')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='เหตุผลที่แก้ไข')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotes.salesdocument')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'เวอร์ชันใบเสนอราคา',
                'verbose_name_plural': 'เวอร์ชันใบเสนอราคา',
                'ordering': ('document', 'revision'),
                'constraints': [models.UniqueConstraint(fields=('document', 'revision'), name='uniq_quote_revision_per_doc')],
            },
        ),
    ]
