# Generated by Django 6.0.5 on 2026-05-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rls_conversation_message'),
        ('quotes', '0006_quotationrevision_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ลูกค้าเปิดดูครั้งแรก'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ลูกค้าเปิดดูล่าสุด'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='source_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='integrations.conversation'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่เปิดดู'),
        ),
    ]
