# Generated by Django 6.0.5 on 2026-05-13 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_salesdocument_first_viewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='ครบกำหนดชำระ'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ออกเอกสารเมื่อ'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='references_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_documents', to='quotes.salesdocument'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='quotes.salesdocument'),
        ),
        migrations.AlterField(
            model_name='documentnumbersequence',
            name='doc_type',
            field=models.CharField(choices=[('quotation', 'ใบเสนอราคา'), ('sales_order', 'ใบสั่งขาย'), ('delivery_note', 'ใบส่งของ'), ('invoice', 'ใบแจ้งหนี้/ใบวางบิล'), ('tax_invoice', 'ใบกำกับภาษี'), ('receipt', 'ใบเสร็จรับเงิน'), ('credit_note', 'ใบลดหนี้'), ('debit_note', 'ใบเพิ่มหนี้'), ('deposit', 'ใบรับเงินมัดจำ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='doc_type',
            field=models.CharField(choices=[('quotation', 'ใบเสนอราคา'), ('sales_order', 'ใบสั่งขาย'), ('delivery_note', 'ใบส่งของ'), ('invoice', 'ใบแจ้งหนี้/ใบวางบิล'), ('tax_invoice', 'ใบกำกับภาษี'), ('receipt', 'ใบเสร็จรับเงิน'), ('credit_note', 'ใบลดหนี้'), ('debit_note', 'ใบเพิ่มหนี้'), ('deposit', 'ใบรับเงินมัดจำ')], default='quotation', max_length=20, verbose_name='ชนิดเอกสาร'),
        ),
    ]
