# Generated by Django 6.0.5 on 2026-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_salesdocument_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='source',
            field=models.CharField(choices=[('manual', 'สร้างเอง'), ('line', 'ไลน์'), ('website', 'เว็บไซต์'), ('email', 'อีเมล')], db_index=True, default='manual', max_length=10, verbose_name='ที่มา'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='status',
            field=models.CharField(choices=[('request', 'คำขอจากลูกค้า'), ('draft', 'ร่าง'), ('pending', 'รออนุมัติ'), ('ready', 'พร้อมส่ง'), ('sent', 'ส่งให้ลูกค้าแล้ว'), ('accepted', 'ลูกค้าตอบรับ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('expired', 'หมดอายุ'), ('cancelled', 'ยกเลิก')], default='draft', max_length=10, verbose_name='สถานะ'),
        ),
    ]
