# Generated by Django 6.0.5 on 2026-05-13 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=80, verbose_name='การกระทำ')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='ชนิดวัตถุ')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='รหัสวัตถุ')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='วัตถุ')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='รายละเอียดการเปลี่ยนแปลง')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กระทำ')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'บันทึกตรวจสอบ',
                'verbose_name_plural': 'บันทึกตรวจสอบ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_9e2202_idx')],
            },
        ),
    ]
