# Generated by Django 6.0.5 on 2026-05-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_tenant_slug_tenantdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อหมวด')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.productcategory')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'หมวดสินค้า',
                'verbose_name_plural': 'หมวดสินค้า',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='รหัส/รุ่น')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='ชื่อ (อังกฤษ)')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('unit', models.CharField(default='ชิ้น', max_length=30, verbose_name='หน่วยนับ')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ราคาขายเริ่มต้น')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='ต้นทุน')),
                ('tax_type', models.CharField(choices=[('vat7', 'VAT 7%'), ('vat0', 'VAT 0% (เช่น ส่งออก)'), ('exempt', 'ยกเว้น VAT'), ('none', 'ไม่คิด VAT')], default='vat7', max_length=10, verbose_name='ภาษี')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='กว้าง (มม.)')),
                ('depth_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='ลึก (มม.)')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='สูง (มม.)')),
                ('material', models.CharField(blank=True, max_length=150, verbose_name='วัสดุ/ผิว')),
                ('finish', models.CharField(blank=True, max_length=150, verbose_name='สี/ผิวสำเร็จ')),
                ('color_code', models.CharField(blank=True, max_length=50, verbose_name='รหัสสี')),
                ('hardware_brand', models.CharField(blank=True, help_text='เช่น บานพับ/รางลิ้นชัก', max_length=100, verbose_name='ยี่ห้ออุปกรณ์')),
                ('standard', models.CharField(blank=True, help_text='เช่น มอก. ...', max_length=100, verbose_name='มาตรฐาน')),
                ('is_bundle', models.BooleanField(default=False, verbose_name='เป็นชุด (มีรายการย่อย)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('tags', models.CharField(blank=True, help_text='คั่นด้วยจุลภาค', max_length=255, verbose_name='แท็ก')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='รูป')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='คำบรรยาย')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'รูปสินค้า',
                'verbose_name_plural': 'รูปสินค้า',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='เช่น เพิ่มไฟ LED ใต้ตู้', max_length=255, verbose_name='ออปชันเสริม')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ราคาเพิ่ม')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ออปชันสินค้า',
                'verbose_name_plural': 'ออปชันสินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='เช่น "W150 / สีโอ๊ค"', max_length=255, verbose_name='รุ่นย่อย')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ราคา')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='ต้นทุน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขาย')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'รุ่นย่อยสินค้า',
                'verbose_name_plural': 'รุ่นย่อยสินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='จำนวน')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.product')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'รายการในชุด',
                'verbose_name_plural': 'รายการในชุด',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='catalog_pro_tenant__750d04_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'code'], name='catalog_pro_tenant__94eca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('tenant', 'code'), name='uniq_product_code_per_tenant'),
        ),
    ]
