# Generated by Django 6.0.5 on 2026-05-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rls'),
        ('tenants', '0013_public_site_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ใช้แสดง chip บนเว็บสาธารณะ · ไม่ใช่สต๊อกจริง', null=True, verbose_name='ลีดไทม์ (วัน)'),
        ),
        migrations.CreateModel(
            name='PortfolioCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200, verbose_name='ลูกค้า')),
                ('year_display', models.CharField(blank=True, help_text='เช่น 2568', max_length=20, verbose_name='ปี (แสดง)')),
                ('scope', models.CharField(blank=True, max_length=500, verbose_name='ขอบเขตงาน')),
                ('spec_summary', models.CharField(blank=True, max_length=500, verbose_name='สเปคสรุป')),
                ('project_value_display', models.CharField(blank=True, help_text='เช่น ~฿342,000', max_length=80, verbose_name='มูลค่า (แสดง)')),
                ('install_days_display', models.CharField(blank=True, max_length=80, verbose_name='ส่ง+ติดตั้ง')),
                ('photo_count', models.PositiveSmallIntegerField(default=0, verbose_name='จำนวนรูป')),
                ('image_primary', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='รูปหลัก')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='รูปรอง')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดแสดง')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ผลงาน',
                'verbose_name_plural': 'ผลงาน',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
